import type { NextPage } from "next";
import Head from "next/head";
import { Track } from "@uniformdev/context-react";
import { IPage } from "../lib/contentstack";
import { PageComponentsList } from "./PageComponentsList";
import { EnrichmentData } from "@uniformdev/context";

export type PageProps = {
  preview: boolean;
  page: IPage;
};

const Page: NextPage<PageProps> = (props) => {
  const { page } = props;
  const enrichments: EnrichmentData[] = [];
  if (page?.context_enrichment_tags?.name) {
    enrichments.push(...page.context_enrichment_tags.name);
  }
  return (
    <Track behavior={enrichments}>
      <Head>
        <title>ContentConn Demo</title>
        <meta
          name="description"
          content="Generated by create next app, modified with typescript, etc"
        />
      </Head>
      {page?.components && <PageComponentsList components={page?.components} />}
    </Track>
  );
};

export default Page;
