import type { NextPage } from "next";
import Head from "next/head";
import { Track } from "@uniformdev/context-react";
import { IPage, ITalk } from "../lib/contentstack";
import { PageComponentsList } from "./PageComponentsList";
import { EnrichmentData } from "@uniformdev/context";
import TalksContext from "../lib/talksContext";

export type PageProps = {
  preview: boolean;
  page: IPage;
  talks: ITalk[] | undefined;
};

const Page: NextPage<PageProps> = ({ page, talks }) => {
  const enrichments: EnrichmentData[] = [];
  if (page?.context_enrichment_tags?.name) {
    enrichments.push(...page.context_enrichment_tags.name);
  }
  return (
    <Track behavior={enrichments}>
      <Head>
        <title>ContentConn Demo</title>
        <meta
          name="description"
          content="Generated by create next app, modified with typescript, etc"
        />
      </Head>
      <TalksContext.Provider value={talks}>
        {page?.components && (
          <PageComponentsList components={page?.components} />
        )}
      </TalksContext.Provider>
    </Track>
  );
};

export default Page;
